// ─── Mock Company Data ─────────────────────────────────────────────────────

export const MOCK_EMPLOYEES = [
  {
    id: 1,
    name: 'Arun Kumar',
    email: 'arun@company.com',
    password: 'arun123',
    role: 'employee',
    role_id: 4,
    department: 'Engineering',
    department_id: 1,
    position: 'Senior Software Engineer',
    phone: '+91 98765 43210',
    joinDate: '2023-01-15',
    skills: ['React', 'Node.js', 'Python', 'TypeScript'],
    performance: 4.8,
    status: 'active',
    salary: '₹8,50,000 / yr',
    tasksCompleted: 42,
    tasksActive: 5,
    leaveBalance: 15,
    address: 'Chennai, Tamil Nadu',
    bio: 'Passionate full-stack developer with 3+ years of experience building scalable enterprise applications.',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    email: 'priya@company.com',
    password: 'priya123',
    role: 'employee',
    role_id: 4,
    department: 'Marketing',
    department_id: 2,
    position: 'Marketing Analyst',
    phone: '+91 98765 43211',
    joinDate: '2022-06-01',
    skills: ['SEO', 'Content Writing', 'Google Analytics', 'Social Media Marketing'],
    performance: 4.5,
    status: 'active',
    salary: '₹7,20,000 / yr',
    tasksCompleted: 38,
    tasksActive: 3,
    leaveBalance: 12,
    address: 'Mumbai, Maharashtra',
    bio: 'Creative marketing analyst specializing in digital campaigns and brand positioning.',
  },
  {
    id: 3,
    name: 'Rahul Patel',
    email: 'rahul@company.com',
    password: 'rahul123',
    role: 'employee',
    role_id: 4,
    department: 'Human Resources',
    department_id: 3,
    position: 'HR Executive',
    phone: '+91 98765 43212',
    joinDate: '2023-08-10',
    skills: ['Recruitment', 'Payroll Processing', 'Employee Training', 'HRMS Tools'],
    performance: 4.6,
    status: 'active',
    salary: '₹6,80,000 / yr',
    tasksCompleted: 29,
    tasksActive: 4,
    leaveBalance: 18,
    address: 'Ahmedabad, Gujarat',
    bio: 'Dedicated HR professional focused on talent acquisition, employee wellness, and organizational development.',
  },
  {
    id: 4,
    name: 'Deepa Nair',
    email: 'manager@company.com',
    password: 'manager123',
    role: 'manager',
    role_id: 3,
    department: 'Engineering',
    department_id: 1,
    position: 'Project Manager',
    phone: '+91 98765 43213',
    joinDate: '2021-03-20',
    skills: ['Project Management', 'Agile / Scrum', 'Team Leadership', 'Risk Analysis'],
    performance: 4.9,
    status: 'active',
    salary: '₹14,00,000 / yr',
    tasksCompleted: 87,
    tasksActive: 8,
    leaveBalance: 20,
    address: 'Bangalore, Karnataka',
    bio: 'Experienced project manager with 8+ years leading cross-functional teams delivering enterprise solutions on time.',
  },
  {
    id: 5,
    name: 'Admin User',
    email: 'admin@company.com',
    password: 'admin123',
    role: 'admin',
    role_id: 1,
    department: 'Administration',
    department_id: 4,
    position: 'System Administrator',
    phone: '+91 98765 43214',
    joinDate: '2020-01-01',
    skills: ['System Administration', 'Security Management', 'Database Operations', 'DevOps'],
    performance: 5.0,
    status: 'active',
    salary: '₹18,00,000 / yr',
    tasksCompleted: 120,
    tasksActive: 10,
    leaveBalance: 22,
    address: 'Hyderabad, Telangana',
    bio: 'Senior system administrator responsible for enterprise infrastructure, security policies, and access management.',
  },
  {
    id: 6,
    name: 'Karthik Raj',
    email: 'karthik@company.com',
    password: 'karthik123',
    role: 'employee',
    role_id: 4,
    department: 'Engineering',
    department_id: 1,
    position: 'Frontend Developer',
    phone: '+91 97654 32109',
    joinDate: '2024-02-01',
    skills: ['Vue.js', 'React', 'Figma', 'CSS3', 'GSAP'],
    performance: 4.3,
    status: 'active',
    salary: '₹7,00,000 / yr',
    tasksCompleted: 18,
    tasksActive: 6,
    leaveBalance: 10,
    address: 'Coimbatore, Tamil Nadu',
    bio: 'Creative frontend developer passionate about pixel-perfect UI and smooth animations.',
  },
  {
    id: 7,
    name: 'Meena Krishnan',
    email: 'meena@company.com',
    password: 'meena123',
    role: 'employee',
    role_id: 4,
    department: 'Human Resources',
    department_id: 3,
    position: 'HR Manager',
    phone: '+91 99887 76655',
    joinDate: '2021-09-14',
    skills: ['Performance Appraisal', 'Conflict Resolution', 'Labour Law', 'Onboarding'],
    performance: 4.7,
    status: 'active',
    salary: '₹10,50,000 / yr',
    tasksCompleted: 55,
    tasksActive: 5,
    leaveBalance: 16,
    address: 'Madurai, Tamil Nadu',
    bio: 'Seasoned HR manager with expertise in performance management and employee relations.',
  },
  {
    id: 8,
    name: 'Suresh Babu',
    email: 'suresh@company.com',
    password: 'suresh123',
    role: 'employee',
    role_id: 4,
    department: 'Finance',
    department_id: 5,
    position: 'Senior Accountant',
    phone: '+91 94455 66778',
    joinDate: '2022-03-07',
    skills: ['Tally ERP', 'GST Filing', 'Financial Modelling', 'MS Excel'],
    performance: 4.4,
    status: 'active',
    salary: '₹9,00,000 / yr',
    tasksCompleted: 33,
    tasksActive: 4,
    leaveBalance: 14,
    address: 'Trichy, Tamil Nadu',
    bio: 'Experienced accountant managing enterprise financials, audits, and GST compliance for 5+ years.',
  },
  {
    id: 9,
    name: 'Anjali Menon',
    email: 'anjali@company.com',
    password: 'anjali123',
    role: 'employee',
    role_id: 4,
    department: 'Marketing',
    department_id: 2,
    position: 'Brand Designer',
    phone: '+91 91234 56789',
    joinDate: '2023-05-15',
    skills: ['Adobe Illustrator', 'Photoshop', 'Brand Strategy', 'Motion Design'],
    performance: 4.6,
    status: 'active',
    salary: '₹8,00,000 / yr',
    tasksCompleted: 24,
    tasksActive: 3,
    leaveBalance: 13,
    address: 'Kochi, Kerala',
    bio: 'Talented brand designer with an eye for aesthetics and deep expertise in visual storytelling.',
  },
  {
    id: 10,
    name: 'Vijay Anand',
    email: 'vijay@company.com',
    password: 'vijay123',
    role: 'employee',
    role_id: 4,
    department: 'Engineering',
    department_id: 1,
    position: 'Backend Engineer',
    phone: '+91 88776 65544',
    joinDate: '2023-11-20',
    skills: ['Django', 'PostgreSQL', 'Redis', 'Docker', 'Kubernetes'],
    performance: 4.5,
    status: 'active',
    salary: '₹9,50,000 / yr',
    tasksCompleted: 21,
    tasksActive: 7,
    leaveBalance: 9,
    address: 'Pune, Maharashtra',
    bio: 'Backend specialist building high-performance APIs and distributed systems.',
  },
  {
    id: 11,
    name: 'Lakshmi Priya',
    email: 'lakshmi@company.com',
    password: 'lakshmi123',
    role: 'employee',
    role_id: 4,
    department: 'Sales',
    department_id: 6,
    position: 'Sales Executive',
    phone: '+91 77665 54433',
    joinDate: '2024-01-10',
    skills: ['Lead Generation', 'CRM Tools', 'Cold Calling', 'Negotiation'],
    performance: 4.2,
    status: 'active',
    salary: '₹6,50,000 / yr',
    tasksCompleted: 15,
    tasksActive: 8,
    leaveBalance: 11,
    address: 'Salem, Tamil Nadu',
    bio: 'Energetic sales executive consistently exceeding quarterly revenue targets through relationship building.',
  },
  {
    id: 12,
    name: 'Balaji Venkat',
    email: 'balaji@company.com',
    password: 'balaji123',
    role: 'employee',
    role_id: 4,
    department: 'Finance',
    department_id: 5,
    position: 'Financial Analyst',
    phone: '+91 66554 43322',
    joinDate: '2022-08-01',
    skills: ['Power BI', 'Excel VBA', 'Risk Assessment', 'Budget Planning'],
    performance: 4.3,
    status: 'on_leave',
    salary: '₹8,80,000 / yr',
    tasksCompleted: 31,
    tasksActive: 2,
    leaveBalance: 6,
    address: 'Vellore, Tamil Nadu',
    bio: 'Financial analyst specializing in data-driven investment analysis and budget forecasting.',
  },
]

// ─── Mock Login ─────────────────────────────────────────────────────────────
export const mockLogin = (email, password) => {
  const found = MOCK_EMPLOYEES.find(
    u => u.email.toLowerCase() === email.toLowerCase() && u.password === password
  )
  if (!found) return null
  const { password: _, ...safeUser } = found
  return {
    access_token: 'mock_token_' + found.id + '_' + Date.now(),
    user: safeUser,
  }
}

// ─── Mock Departments ────────────────────────────────────────────────────────
export const MOCK_DEPARTMENTS = [
  { id: 1, department_name: 'Engineering',       head: 'Deepa Nair',   employee_count: 4, budget: '₹45,00,000', description: 'Product development, infrastructure & QA' },
  { id: 2, department_name: 'Marketing',         head: 'Priya Sharma', employee_count: 2, budget: '₹18,00,000', description: 'Brand growth, digital campaigns & design' },
  { id: 3, department_name: 'Human Resources',   head: 'Meena Krishnan', employee_count: 2, budget: '₹12,00,000', description: 'Talent acquisition, payroll & compliance' },
  { id: 4, department_name: 'Administration',    head: 'Admin User',   employee_count: 1, budget: '₹10,00,000', description: 'IT infrastructure, security & admin ops' },
  { id: 5, department_name: 'Finance',           head: 'Suresh Babu',  employee_count: 2, budget: '₹22,00,000', description: 'Accounting, budgeting & financial reporting' },
  { id: 6, department_name: 'Sales',             head: 'Lakshmi Priya', employee_count: 1, budget: '₹15,00,000', description: 'Revenue generation & client management' },
]

// ─── Mock Projects ───────────────────────────────────────────────────────────
export const MOCK_PROJECTS = [
  { project_id: 1, project_name: 'EnterpriseSync v2',  description: 'Next-gen enterprise platform with AI analytics and real-time dashboards', manager_name: 'Deepa Nair',    priority: 'critical', completion_percentage: 58, status: 'active',    start_date: '2026-06-01', end_date: '2026-10-31', team: ['Arun Kumar', 'Karthik Raj', 'Vijay Anand'] },
  { project_id: 2, project_name: 'Mobile App Dev',      description: 'Cross-platform iOS & Android employee self-service app',                 manager_name: 'Deepa Nair',    priority: 'critical', completion_percentage: 35, status: 'active',    start_date: '2026-06-15', end_date: '2026-12-31', team: ['Arun Kumar', 'Karthik Raj'] },
  { project_id: 3, project_name: 'Database Migration',  description: 'Migrate 8-year-old legacy Oracle DB to PostgreSQL with zero downtime',  manager_name: 'Vijay Anand',   priority: 'medium',   completion_percentage: 100, status: 'completed', start_date: '2026-04-01', end_date: '2026-06-30', team: ['Vijay Anand', 'Arun Kumar'] },
  { project_id: 4, project_name: 'AI Analytics Module', description: 'ML-powered burnout detection, workload rebalancing & predictive risks',  manager_name: 'Admin User',    priority: 'high',     completion_percentage: 22, status: 'active',    start_date: '2026-08-01', end_date: '2026-11-30', team: ['Vijay Anand', 'Arun Kumar', 'Balaji Venkat'] },
  { project_id: 5, project_name: 'Brand Revamp 2026',   description: 'Full visual identity overhaul — logo, design system & marketing collateral', manager_name: 'Priya Sharma', priority: 'medium',   completion_percentage: 70, status: 'active',    start_date: '2026-05-10', end_date: '2026-08-31', team: ['Anjali Menon', 'Priya Sharma'] },
  { project_id: 6, project_name: 'HR Policy Automation',description: 'Digitize leave management, appraisals, and compliance workflows',       manager_name: 'Meena Krishnan', priority: 'low',    completion_percentage: 45, status: 'active',    start_date: '2026-07-01', end_date: '2026-09-30', team: ['Rahul Patel', 'Meena Krishnan'] },
  { project_id: 7, project_name: 'Sales CRM Integration', description: 'Integrate Salesforce CRM with internal lead pipeline tracking',      manager_name: 'Lakshmi Priya', priority: 'high',     completion_percentage: 15, status: 'active',    start_date: '2026-08-01', end_date: '2026-10-15', team: ['Lakshmi Priya', 'Arun Kumar'] },
  { project_id: 8, project_name: 'Q3 Financial Audit',  description: 'Internal audit for Q3 revenues, expenses, and GST compliance',         manager_name: 'Suresh Babu',   priority: 'high',     completion_percentage: 80, status: 'active',    start_date: '2026-07-15', end_date: '2026-08-15', team: ['Suresh Babu', 'Balaji Venkat'] },
]

// ─── Mock Task Data per user ─────────────────────────────────────────────────
export const MOCK_TASKS = {
  1: [
    { id: 101, title: 'Complete UI Design Review',         status: 'in_progress', priority: 'high',   due: '2026-08-05', project: 'EnterpriseSync v2' },
    { id: 102, title: 'Update REST API Documentation',     status: 'todo',        priority: 'medium', due: '2026-08-10', project: 'Backend Infra' },
    { id: 103, title: 'Fix Authentication Bug #342',       status: 'completed',   priority: 'high',   due: '2026-07-30', project: 'Security Patch' },
    { id: 104, title: 'Deploy to Production Server',       status: 'todo',        priority: 'high',   due: '2026-08-15', project: 'EnterpriseSync v2' },
    { id: 105, title: 'Code Review - Team PRs',            status: 'in_progress', priority: 'low',    due: '2026-08-03', project: 'Eng Excellence' },
    { id: 106, title: 'Integrate Payment Gateway API',     status: 'todo',        priority: 'high',   due: '2026-08-20', project: 'Mobile App Dev' },
    { id: 107, title: 'Write Unit Tests for Auth Module',  status: 'todo',        priority: 'medium', due: '2026-08-12', project: 'EnterpriseSync v2' },
    { id: 108, title: 'Optimize DB Query Performance',     status: 'in_progress', priority: 'high',   due: '2026-08-08', project: 'AI Analytics Module' },
  ],
  2: [
    { id: 201, title: 'Q3 Campaign Strategy',              status: 'in_progress', priority: 'high',   due: '2026-08-01', project: 'Marketing Q3' },
    { id: 202, title: 'Social Media Calendar Aug-Sep',     status: 'completed',   priority: 'medium', due: '2026-07-28', project: 'Brand Revamp 2026' },
    { id: 203, title: 'SEO Audit Report',                  status: 'todo',        priority: 'medium', due: '2026-08-12', project: 'Digital Growth' },
    { id: 204, title: 'Write Blog: AI in HR Management',   status: 'todo',        priority: 'low',    due: '2026-08-18', project: 'Content Strategy' },
    { id: 205, title: 'Review Competitor Landscape',       status: 'in_progress', priority: 'medium', due: '2026-08-06', project: 'Market Research' },
  ],
  3: [
    { id: 301, title: 'New Hire Onboarding - 3 Candidates', status: 'in_progress', priority: 'high', due: '2026-08-03', project: 'Recruitment Q3' },
    { id: 302, title: 'Monthly Payroll Processing',          status: 'todo',        priority: 'high', due: '2026-08-01', project: 'Payroll Ops' },
    { id: 303, title: 'Employee Satisfaction Survey',        status: 'completed',   priority: 'medium', due: '2026-07-25', project: 'HR Analytics' },
    { id: 304, title: 'Update HR Policy Manual',             status: 'todo',        priority: 'low',  due: '2026-08-20', project: 'Compliance' },
    { id: 305, title: 'Schedule Q3 Performance Reviews',     status: 'todo',        priority: 'medium', due: '2026-08-15', project: 'HR Analytics' },
  ],
  4: [
    { id: 401, title: 'Sprint Planning - Week 31',           status: 'completed', priority: 'high',   due: '2026-07-29', project: 'EnterpriseSync v2' },
    { id: 402, title: 'Resource Allocation Review',          status: 'in_progress', priority: 'high', due: '2026-08-02', project: 'Project Mgmt' },
    { id: 403, title: 'Stakeholder Status Report',           status: 'todo',      priority: 'medium', due: '2026-08-07', project: 'EnterpriseSync v2' },
    { id: 404, title: 'Risk Assessment - Mobile App Dev',    status: 'in_progress', priority: 'critical', due: '2026-08-01', project: 'Mobile App Dev' },
    { id: 405, title: 'Update Project Roadmap Q4',           status: 'todo',      priority: 'medium', due: '2026-08-10', project: 'Project Mgmt' },
    { id: 406, title: 'Vendor Contract Review',              status: 'todo',      priority: 'low',    due: '2026-08-22', project: 'Procurement' },
  ],
  5: [
    { id: 501, title: 'System Security Patch Update',        status: 'completed', priority: 'critical', due: '2026-07-30', project: 'IT Ops' },
    { id: 502, title: 'Set Up CI/CD Pipeline for v2',        status: 'in_progress', priority: 'high', due: '2026-08-05', project: 'EnterpriseSync v2' },
    { id: 503, title: 'Firewall Rule Audit',                 status: 'todo',      priority: 'high',   due: '2026-08-08', project: 'Security' },
    { id: 504, title: 'Backup Verification - Monthly',       status: 'completed', priority: 'medium', due: '2026-07-28', project: 'IT Ops' },
    { id: 505, title: 'AWS Cost Optimization Review',        status: 'in_progress', priority: 'medium', due: '2026-08-12', project: 'Infra' },
    { id: 506, title: 'Onboard Dev Team to New K8s Cluster', status: 'todo',      priority: 'high',   due: '2026-08-18', project: 'DevOps' },
  ],
}

// ─── Mock Assets ─────────────────────────────────────────────────────────────
export const MOCK_ASSETS = [
  { id: 1, name: 'MacBook Pro M3 14"',   category: 'Laptop',    assigned_to: 'Arun Kumar',    status: 'in_use',    condition: 'Excellent', serial: 'MBP-M3-2024-001', purchase_date: '2024-02-01', value: '₹1,85,000' },
  { id: 2, name: 'MacBook Air M2',        category: 'Laptop',    assigned_to: 'Karthik Raj',   status: 'in_use',    condition: 'Good',      serial: 'MBA-M2-2024-002', purchase_date: '2024-03-15', value: '₹1,20,000' },
  { id: 3, name: 'Dell XPS 15',           category: 'Laptop',    assigned_to: 'Vijay Anand',   status: 'in_use',    condition: 'Good',      serial: 'DELL-XPS-2023-03', purchase_date: '2023-11-20', value: '₹1,40,000' },
  { id: 4, name: 'Samsung 27" 4K Monitor',category: 'Monitor',   assigned_to: 'Arun Kumar',    status: 'in_use',    condition: 'Excellent', serial: 'SAM-4K-2024-001', purchase_date: '2024-01-10', value: '₹45,000' },
  { id: 5, name: 'iPhone 15 Pro',         category: 'Phone',     assigned_to: 'Deepa Nair',    status: 'in_use',    condition: 'Excellent', serial: 'IP15P-2024-004', purchase_date: '2024-01-01', value: '₹1,35,000' },
  { id: 6, name: 'Ergonomic Office Chair',category: 'Furniture', assigned_to: 'Priya Sharma',  status: 'in_use',    condition: 'Good',      serial: 'CHAIR-ERG-002',   purchase_date: '2023-06-01', value: '₹18,000' },
  { id: 7, name: 'HP LaserJet Pro',       category: 'Printer',   assigned_to: 'Unassigned',    status: 'available', condition: 'Good',      serial: 'HPLJ-2022-001',   purchase_date: '2022-09-01', value: '₹25,000' },
  { id: 8, name: 'Logitech MX Keys Combo',category: 'Peripheral',assigned_to: 'Meena Krishnan',status: 'in_use',    condition: 'Excellent', serial: 'LG-MXK-2024-007', purchase_date: '2024-02-20', value: '₹12,000' },
  { id: 9, name: 'MacBook Pro M3 16"',    category: 'Laptop',    assigned_to: 'Admin User',    status: 'in_use',    condition: 'Excellent', serial: 'MBP-M3-2024-009', purchase_date: '2024-01-15', value: '₹2,20,000' },
  { id: 10, name: 'iPad Pro 12.9"',       category: 'Tablet',    assigned_to: 'Rahul Patel',   status: 'in_use',    condition: 'Good',      serial: 'IPAD-PRO-2023-010', purchase_date: '2023-09-01', value: '₹95,000' },
]

// ─── Mock Leave Requests ─────────────────────────────────────────────────────
export const MOCK_LEAVE_REQUESTS = [
  { id: 1, employee: 'Balaji Venkat',  type: 'Medical Leave',   from: '2026-07-28', to: '2026-08-05', days: 8,  reason: 'Hospitalisation - Appendix surgery recovery', status: 'approved', applied_on: '2026-07-26' },
  { id: 2, employee: 'Karthik Raj',    type: 'Casual Leave',    from: '2026-08-09', to: '2026-08-10', days: 2,  reason: 'Personal function at hometown',                status: 'pending',  applied_on: '2026-07-30' },
  { id: 3, employee: 'Anjali Menon',   type: 'Earned Leave',    from: '2026-08-15', to: '2026-08-22', days: 6,  reason: 'Family vacation — pre-planned',                status: 'pending',  applied_on: '2026-07-29' },
  { id: 4, employee: 'Lakshmi Priya',  type: 'Sick Leave',      from: '2026-07-31', to: '2026-07-31', days: 1,  reason: 'Fever and viral infection',                    status: 'approved', applied_on: '2026-07-31' },
  { id: 5, employee: 'Rahul Patel',    type: 'Paternity Leave', from: '2026-08-20', to: '2026-09-03', days: 15, reason: 'Newborn child',                                status: 'pending',  applied_on: '2026-07-25' },
  { id: 6, employee: 'Suresh Babu',    type: 'Casual Leave',    from: '2026-08-02', to: '2026-08-02', days: 1,  reason: 'Bank related work',                            status: 'rejected', applied_on: '2026-07-28', rejection_reason: 'Quarterly audit period — no leave' },
  { id: 7, employee: 'Vijay Anand',    type: 'Work From Home',  from: '2026-08-04', to: '2026-08-08', days: 5,  reason: 'Flat shifting — moving to new city',          status: 'approved', applied_on: '2026-07-27' },
  { id: 8, employee: 'Meena Krishnan', type: 'Earned Leave',    from: '2026-08-25', to: '2026-08-29', days: 5,  reason: 'Annual family trip',                          status: 'pending',  applied_on: '2026-07-30' },
]

// ─── Mock Notifications ──────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS = [
  { id: 1,  type: 'deadline',  title: '⚠️ Task Deadline Tomorrow',         message: '"Deploy to Production" is due tomorrow. Complete immediately!', time: new Date(Date.now() - 5 * 60000).toISOString(),   read: false, priority: 'high' },
  { id: 2,  type: 'leave',     title: '📋 Leave Request Pending',           message: 'Karthik Raj applied for 2 days casual leave. Action required.', time: new Date(Date.now() - 22 * 60000).toISOString(),  read: false, priority: 'medium' },
  { id: 3,  type: 'risk',      title: '🚨 High Risk Alert — Mobile App',    message: 'Risk score jumped to 88%. Predicted 24-day delay. Take action!', time: new Date(Date.now() - 45 * 60000).toISOString(),  read: false, priority: 'critical' },
  { id: 4,  type: 'system',    title: '✅ Security Patch Deployed',          message: 'All servers patched successfully. Zero downtime achieved.',      time: new Date(Date.now() - 70 * 60000).toISOString(),  read: true,  priority: 'low' },
  { id: 5,  type: 'task',      title: '✅ Task Completed',                  message: 'Arun Kumar marked "Fix Auth Bug #342" as completed.',           time: new Date(Date.now() - 90 * 60000).toISOString(),  read: true,  priority: 'low' },
  { id: 6,  type: 'hr',        title: '📊 Payroll Processing Due',          message: 'August payroll deadline is August 1st. Initiate now.',          time: new Date(Date.now() - 2 * 3600000).toISOString(), read: false, priority: 'high' },
  { id: 7,  type: 'leave',     title: '✅ Leave Approved',                  message: 'Your leave request from Aug 4–8 has been approved.',            time: new Date(Date.now() - 3 * 3600000).toISOString(), read: true,  priority: 'low' },
  { id: 8,  type: 'risk',      title: '⚡ Workload Imbalance Detected',      message: 'Arun Kumar is at 92% capacity. Consider task redistribution.',  time: new Date(Date.now() - 5 * 3600000).toISOString(), read: false, priority: 'medium' },
  { id: 9,  type: 'system',    title: '💾 Backup Completed',                message: 'Monthly system backup verified. All 14 TB secured to S3.',      time: new Date(Date.now() - 8 * 3600000).toISOString(), read: true,  priority: 'low' },
  { id: 10, type: 'task',      title: '📌 New Task Assigned to You',        message: '"Integrate Payment Gateway API" added to your task list.',      time: new Date(Date.now() - 10 * 3600000).toISOString(), read: false, priority: 'medium' },
]

// ─── Mock Dashboard Stats ────────────────────────────────────────────────────
export const MOCK_STATS = {
  total_employees: 12,
  active_projects: 7,
  high_risk_projects_count: 2,
  pending_tasks: 18,
  tasks_completed_this_month: 24,
  pending_leave_requests: 4,
  workload_imbalance_alerts: 3,
  departments: 6,
  assets_in_use: 9,
  assets_available: 1,
}

// ─── Mock Dashboard Charts ───────────────────────────────────────────────────
export const MOCK_CHART_DATA = {
  project_status: [
    { name: 'Active',     value: 6 },
    { name: 'Completed',  value: 1 },
    { name: 'On Hold',    value: 1 },
  ],
  employee_workload: [
    { name: 'Arun Kumar',     active_tasks: 8 },
    { name: 'Vijay Anand',    active_tasks: 7 },
    { name: 'Lakshmi Priya',  active_tasks: 8 },
    { name: 'Karthik Raj',    active_tasks: 6 },
    { name: 'Deepa Nair',     active_tasks: 8 },
    { name: 'Rahul Patel',    active_tasks: 4 },
    { name: 'Priya Sharma',   active_tasks: 3 },
  ],
  department_distribution: [
    { name: 'Engineering',    value: 4 },
    { name: 'Marketing',      value: 2 },
    { name: 'Human Resources',value: 2 },
    { name: 'Administration', value: 1 },
    { name: 'Finance',        value: 2 },
    { name: 'Sales',          value: 1 },
  ],
  monthly_tasks: [
    { month: 'Mar', completed: 14, created: 18 },
    { month: 'Apr', completed: 19, created: 22 },
    { month: 'May', completed: 23, created: 26 },
    { month: 'Jun', completed: 28, created: 30 },
    { month: 'Jul', completed: 24, created: 32 },
    { month: 'Aug', completed: 6,  created: 12 },
  ],
  performance_trend: [
    { month: 'Mar', score: 4.1 },
    { month: 'Apr', score: 4.3 },
    { month: 'May', score: 4.5 },
    { month: 'Jun', score: 4.4 },
    { month: 'Jul', score: 4.7 },
    { month: 'Aug', score: 4.8 },
  ],
}

// ─── Mock Activity / Audit Logs ──────────────────────────────────────────────
export const MOCK_AUDIT_LOGS = [
  { id: 1,  action: 'LOGIN',          resource: 'Admin User logged in from 192.168.1.10',               timestamp: new Date(Date.now() -   2 * 60000).toISOString() },
  { id: 2,  action: 'CREATE',         resource: 'New employee "Karthik Raj" added to Engineering',      timestamp: new Date(Date.now() -   8 * 60000).toISOString() },
  { id: 3,  action: 'UPDATE',         resource: 'Project "EnterpriseSync v2" status → In Progress',    timestamp: new Date(Date.now() -  15 * 60000).toISOString() },
  { id: 4,  action: 'ASSIGN',         resource: 'Task "API Integration" assigned to Priya Sharma',     timestamp: new Date(Date.now() -  28 * 60000).toISOString() },
  { id: 5,  action: 'LEAVE APPROVED', resource: 'Leave request #12 approved for Rahul Patel',          timestamp: new Date(Date.now() -  45 * 60000).toISOString() },
  { id: 6,  action: 'ASSET ASSIGNED', resource: 'MacBook Pro M3 assigned to Arun Kumar',               timestamp: new Date(Date.now() -  62 * 60000).toISOString() },
  { id: 7,  action: 'DELETE',         resource: 'Obsolete task "Legacy Migration" removed',             timestamp: new Date(Date.now() -  90 * 60000).toISOString() },
  { id: 8,  action: 'ROLE CHANGE',    resource: 'Meena Krishnan role updated: Employee → HR Manager',  timestamp: new Date(Date.now() - 120 * 60000).toISOString() },
  { id: 9,  action: 'CREATE',         resource: 'New project "Sales CRM Integration" created',         timestamp: new Date(Date.now() - 180 * 60000).toISOString() },
  { id: 10, action: 'RISK ALERT',     resource: 'Mobile App Dev risk score escalated to 88% (Critical)', timestamp: new Date(Date.now() - 200 * 60000).toISOString() },
]
